### ISSUE TITLE
kcc make segfaults on cygwin64

### ISSUE THREAD

**Issue by pimathbrainiac** [KnightOS/KnightOS#306]
when making the template c project, I get a segfault. I'm using cygwin64 running on a Windows 8.1 64 bit machine.

$ make
mkdir -p bin
kcc -I .knightos/include/ -I .knightos/ -I ./ -S --std-c99 main.c -o bin/main.asm
Caught signal 11: SIGSEGV
.knightos/sdk.make:15: recipe for target 'bin/main.asm' failed
make: *** [bin/main.asm] Error 1

**Comment by SirCmpwn** [comment]
Can you run it again with valgrind?

**Comment by pimathbrainiac** [comment]
Valgrind does not support cygwin. It says so when I configure.

**Comment by SirCmpwn** [comment]
Huh. Well, if you can figure some other way of getting a stack trace that'd be great.

**Comment by pimathbrainiac** [comment]
Here's a backtrace from gdb:

#0  0x000000010047eff3 in addSet ()
#1  0x000000010050f64c in main ()
