### ISSUE TITLE
Cygwin Z80e tests.exe Segmentation-Fault Caused by Unhandled NULL Pointer

### ISSUE THREAD

**Issue by TheElementalOfCreation** [KnightOS/KnightOS#374]
Whenever I try to run z80e's test.exe program, I get a segmentation fault caused by globals.objects being a null pointer. Below is the log from gdb. I don't know why it is a null pointer at that point in time, but it is.
```
Starting program: /cygdrive/c/Users/Creation/Downloads/calculator/z80e-master/z80e-master/frontends/test/bin/tests.exe
[New Thread 11016.0x4608]
[New Thread 11016.0x20cc]
[New Thread 11016.0x46b4]
[New Thread 11016.0x4d4]
[New Thread 11016.0x4f94]
Testing performance .......................................executed 1,000,000 cycles in 15.000000 milliseconds (~66.666667 MHz)
..........................................Instruction tests....
Testing ADD A, r ..........................................PASS
Testing ADC A, r ..........................................PASS
Testing SUB A, r ..........................................PASS
Testing SBC A, r ..........................................PASS
Testing AND A, r ..........................................PASS
Testing XOR A, r ..........................................PASS
Testing OR A, r ...........................................PASS
Testing CP r ..............................................PASS
Testing RST y .............................................PASS
Testing DJNZ d ............................................PASS
Testing JR d ..............................................PASS
Testing JR cc, d ..........................................PASS
Testing LD rp, nn .........................................PASS
Testing ADD HL, rp ........................................PASS
Testing LD (BC), A ........................................PASS
Testing LD (nn), HL .......................................PASS
Testing LD (nn), A ........................................PASS
Testing LD HL, (nn) .......................................PASS
Testing LD A, (nn) ........................................PASS
Testing INC rp ............................................PASS
Testing INC r .............................................PASS
Testing DEC rp ............................................PASS
Testing DEC r .............................................PASS
Testing LD r, n ...........................................PASS
Testing RLCA ..............................................PASS
Testing RRCA ..............................................PASS
Testing RLA ...............................................PASS
Testing RRA ...............................................PASS
Testing CPL ...............................................PASS
Testing DAA ...............................................PASS
Testing LD r, r ...........................................PASS
Testing POP rp2 ...........................................PASS
Testing RET cc ............................................PASS
Testing RET ...............................................PASS
Testing EXX ...............................................PASS
Testing JP (HL) ...........................................PASS
Testing LD SP, HL .........................................PASS
Testing JP cc, nn .........................................PASS
Testing JP nn .............................................PASS
Testing OUT (n), A ........................................PASS
Testing IN A, (n) .........................................PASS
Testing EX (SP), HL .......................................PASS
Testing EX DE, HL .........................................PASS
Testing CALL cc, nn .......................................PASS
Testing PUSH rp2 ..........................................PASS
Testing CALL nn ...........................................PASS
Testing alu[y] n ..........................................PASS
Testing LD (IX,IY), A / LD A, (IX,IY) .....................PASS
Testing JP IX / JP IY .....................................PASS
Testing ADD IX, rp ........................................PASS
Testing prefix reset ......................................PASS
Testing index offsets .....................................PASS
Testing IXH/IXL ...........................................PASS
Testing interrupt mode set ................................PASS
Testing RLC r .............................................PASS
Testing RRC r .............................................PASS
Testing RL r ..............................................PASS
Testing RR r ..............................................PASS
Testing SLA r .............................................PASS
Testing SRA r .............................................PASS
Testing SLL r .............................................PASS
Testing SRL r .............................................PASS
Testing BIT y, r ..........................................PASS
Testing RES y, r ..........................................PASS
Testing SET y, r ..........................................PASS
Testing EI/DI .............................................PASS
Testing NEG ...............................................PASS
Testing IN (C) ............................................PASS
Testing IN r, (C) .........................................PASS
Testing OUT (C), 0 ........................................PASS
Testing OUT (C), r ........................................PASS
Testing SBC HL, rp ........................................PASS
Testing ADC HL, rp ........................................PASS
Testing LD (nn), rp .......................................PASS
Testing LD rp, (nn) .......................................PASS
Testing LD A, I ...........................................PASS
Testing RRD/RLD ...........................................PASS
Testing LDI ...............................................PASS
Testing LDIR ..............................................PASS
Testing LDD ...............................................PASS
Testing LDDR ..............................................PASS
Testing CPI ...............................................PASS
Testing CPD ...............................................PASS
Testing CPIR ..............................................PASS
Testing CPDR ..............................................PASS
Testing INI ...............................................PASS
Testing IND ...............................................PASS
Testing INIR ..............................................PASS
Testing INDR ..............................................PASS
Testing OUTI ..............................................PASS
Testing OUTD ..............................................PASS
Testing OTIR ..............................................PASS
Testing OTDR ..............................................PASS
............................................Interrupt tests....
Testing mode 1 interrupts .................................PASS
Testing mode 2 interrupts .................................PASS
.................................................Port tests....
Testing port 0x01 (keyboard) ..............................PASS
Testing port 0x02 (status) ................................PASS
Testing port 0x04, 0x05, 0x06, 0x07 (mapping, TI-83+) .....PASS
Testing port 0x04, 0x05, 0x06, 0x07 (mapping, Others) .....PASS
Testing port 0x00 (link port) .............................PASS
Testing port 0x0A (link assist rx) ........................Receiving BE via link port
Receiving EF via link port
FAIL 3
Testing port 0x0D (link assist tx) ........................FAIL 2
.............................................Debugger tests....
Testing debugger_init() ...................................PASS
Testing find_best_command() ...............................PASS
Testing Commandline parser ................................PASS

Thread 1 "tests" received signal SIGSEGV, Segmentation fault.
0x0000000100411840 in try_from_sourcemap (memory=0xffffcaf0, map=0xffffca68, entry=0xffffca60)
    at /cygdrive/c/Users/Creation/Downloads/calculator/z80e-master/z80e-master/libz80e/src/disassembler/disassemble.c:156
156             for (i = 0; i < globals.objects->length; ++i) {
```

And this as the stackdump:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00100411840
rax=0000000000000000 rbx=0000000000000026 rcx=00000000FFFFCAF0
rdx=00000000FFFFCA68 rsi=0000000180261320 rdi=0000000080808000
r8 =00000000FFFFCA60 r9 =0000000180144890 r10=0000000100000000
r11=0000000100408BB0 r12=000000018022CDD0 r13=00000000FFFFCC7C
r14=0000000000000000 r15=00000000FFFFCC7C
rbp=00000000FFFFCA00 rsp=00000000FFFFC9B0
program=C:\Users\Creation\Downloads\calculator\z80e-master\z80e-master\frontends\test\bin\tests.exe, pid 13872, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFCA00  00100411840 (000FFFFCA68, 000FFFFCA60, 00000000000, 00180144AA1)
000FFFFCAC0  0010041260F (00100402D7F, 000FFFFCC00, 0018019464E, 00100402DFC)
000FFFFCB20  00100402E9E (00100420538, 000FFFFCACC, 00180144890, 00049435341)
000FFFFCBB0  00100408BD6 (0018022CDD0, 000FFFFCC7C, 00000000000, 000FFFFCCD0)
000FFFFCBB0  00100408C71 (000FFFFCC00, FF0700010302FF00, 00180049DAA, 000FFFFCCD0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

Oh, and `bt full` on tests.exe gives me:
```
(gdb) bt full
#0  0x0000000100411840 in try_from_sourcemap (memory=0xffffcaf0, map=0xffffca68, entry=0xffffca60)
    at /cygdrive/c/Users/Creation/Downloads/calculator/git/z80-cygwin/z80e/libz80e/src/disassembler/disassemble.c:156
        i = 0
        current = 0
        offset = 0
#1  0x000000010041260f in parse_instruction (memory=0xffffcaf0, write_p=0x100402d7f <dis_write>, knightos=false)
    at /cygdrive/c/Users/Creation/Downloads/calculator/git/z80-cygwin/z80e/libz80e/src/disassembler/disassemble.c:455
        map = 0x0
        entry = 0x0
        start_mem = 0
        context = {prefix = 0, memory = 0x18014b578 <pthread_mutex_unlock(pthread_mutex_t*)+72>, {opcode = 10 '\n', {
              z = 2 '\002', y = 1 '\001', x = 0 '\000'}, {q = 1 '\001', p = 0 '\000'}}, write = 0x800f5e10}
        data = 0 '\000'
        write = 0x18020f890 <reent_data+1520>
#2  0x0000000100402e9e in test_disassembler ()
    at /cygdrive/c/Users/Creation/Downloads/calculator/git/z80-cygwin/z80e/frontends/test/tests/disassembler.c:28
        tests = ":4\022\335\313\022", <incomplete sequence \375\066\020\040>
        mem = {read_byte = 0x100402dfc <dis_read_byte>, current = 0, extra_data = 0x0}
#3  0x0000000100408bd6 in run_all ()
    at /cygdrive/c/Users/Creation/Downloads/calculator/git/z80-cygwin/z80e/frontends/test/test.c:196
        length = -1
        result = 0
        passed = 103
        failed = 2
        i = 110
        min_width = 50
#4  0x0000000100408c71 in main (argc=1, argv=0xffffcc00)
    at /cygdrive/c/Users/Creation/Downloads/calculator/git/z80-cygwin/z80e/frontends/test/test.c:215
No locals.
(gdb)
```

And messing around with print gives me this:
```
(gdb) print globals
$1 = {pcalls = 0x0, objects = 0x0}
(gdb) print globals.objects
$2 = (list_t *) 0x0
(gdb) print globals.objects->length
Cannot access memory at address 0x4
```

When running z80e-sdl.exe I do not get this error, so I would assume tests.exe is accidentally skipping a step that would set globals.objects to something that is NOT a null pointer.

**Comment by pixelherodev** [comment]
As I no longer have a Windows computer, I cannot investigate this.

**Comment by pixelherodev** [comment]
Though, this might be a cross-platform issue. Will run the tests locally later.

**Comment by pixelherodev** [comment]
Can now confirm this issue is cross-platform; apologies for the... very, very long delay.

**Comment by pixelherodev** [comment]
The last test - the disassembler test - is broken. I get a backtrace identical to yours on linux-arm64.

**Comment by pixelherodev** [comment]
Found and fixed.
